#!/usr/bin/env bash
#superstitious numbers loop
x=1
while [ $x -le 20 ]
do echo "$x"
   ((x++))
   case "$x" in
       5) echo "bad luck from china"
	  ;;
       10) echo "bad luck form japan"
	   ;;
       18) echo "bad luck form italy"
	   ;;
   esac
done

    
      
      
