#!/usr/bin/env bash
#superstitious numbers loop
x=1
while [ $x -le 20 ];
do echo "$x"
   ((x++))
   case "$x" in
       4) echo "bad luck from china"
	  ;;
       9) echo "bad luck fromm japan"
	   ;;
       17) echo "bad luck fromm italy"
	   ;;
   esac
done

    
      
      
